project:
  type: website
  output-dir: docs

website:
  title: "Cristina Jackson"
  navbar:
    left:
      - href: finance.qmd
        text: PG&E Valuation

format:
  html:
    theme: [yeti, styles.scss]
    toc: false
    page-layout: full
    smooth-scroll: true
    code-fold: true

execute:
  freeze: auto
  echo: false

editor: visual

