project:
  type: website
  output-dir: docs

website:
  title: "Cristina Jackson"

format:
  html:
    theme: [cosmo, styles.scss]
    toc: false
    page-layout: full
    smooth-scroll: true
    code-fold: true

execute:
  freeze: auto
  echo: false

editor: visual

