project:
  type: website
  output-dir: docs

website:
  title: "cristinajacks0n.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - interests.qmd
      - resume.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

